-- Drop table

-- DROP TABLE public.request_header

CREATE TABLE public.request_header (
	req_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	address varchar(255) NULL,
	assiged_to_emp_id int4 NULL,
	comments varchar(255) NULL,
	completion_datetime timestamp NULL,
	customer_id int4 NULL,
	email varchar(255) NULL,
	first_name varchar(255) NOT NULL,
	last_name varchar(255) NULL,
	phone varchar(255) NULL,
	preferred_contact_method varchar(255) NULL,
	priority varchar(255) NULL,
	request_datetime timestamp NULL,
	service_type varchar(255) NULL,
	status varchar(255) NULL,
	symptoms varchar(255) NULL,
	vendor_id int4 NULL,
	CONSTRAINT request_header_pkey PRIMARY KEY (req_id)
)
WITH (
	OIDS=FALSE
) ;

-- Permissions

ALTER TABLE public.request_header OWNER TO postgres;
