-- Drop table

-- DROP TABLE public.vehicle_service_details

CREATE TABLE public.vehicle_service_details (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	vehicle_location varchar(255) NULL,
	vehicle_make varchar(255) NULL,
	vehicle_model varchar(255) NULL,
	vehicle_year varchar(255) NULL,
	vendor_id int4 NULL,
	vin varchar(255) NULL,
	req_id int4 NULL,
	CONSTRAINT vehicle_service_details_pkey PRIMARY KEY (id)
)
WITH (
	OIDS=FALSE
) ;

-- Permissions

ALTER TABLE public.vehicle_service_details OWNER TO postgres;